name: Create mltbx package

on:
  workflow_dispatch:

jobs:
  create_mltbx:
    name: Create mltbx package
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
          release: R2024a
      - name: Build package
        uses: matlab-actions/run-build@v2
        with:
          tasks: package
      - name: Store package
        uses: actions/upload-artifact@v4
        with:
          name: mltbx
          path: release/*.mltbx

# cspell:words mltbx
