name: Release mltbx package

on:
  workflow_dispatch:
    inputs:
      max-matlab-release:
        required: false
        type: string
      version-number:
        required: true
        type: string

jobs:
  create_mltbx:
    name: Create mltbx package
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
          release: R2024a
      - name: Build package
        uses: matlab-actions/run-build@v2
        with:
          tasks: package
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*.mltbx"
          draft: true
          commit: main
          tag: v${{ github.event.inputs.version-number }}

# cspell:words mltbx ncipollo
